import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'user-stories',
    // The Skills/Plugins hubs live in the navbar. On mobile Docusaurus opens the drawer on the doc
    // sidebar, with the navbar a "Back to main menu" tap away, so without these links the hubs are
    // undiscoverable on a phone.
    {type: 'link', label: 'Browse Skills', href: '/skills'},
    {type: 'link', label: 'Browse Plugins', href: '/plugins'},
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: true,
      items: [
        'getting-started/quickstart',
        'getting-started/installation',
        'getting-started/platform-support',
        'getting-started/termux',
        'getting-started/nix-setup',
        'getting-started/updating',
        'getting-started/learning-path',
      ],
    },
    {
      type: 'category',
      label: 'Using Hermes',
      collapsed: true,
      items: [
        'user-guide/cli',
        'user-guide/tui',
        'user-guide/desktop',
        'user-guide/bot-mode',
        'user-guide/windows-native',
        'user-guide/windows-wsl-quickstart',
        'user-guide/switching-to-source',
        'user-guide/configuration',
        'user-guide/managed-scope',
        'user-guide/configuring-models',
        {
          type: 'category',
          label: 'Secrets',
          collapsed: true,
          items: [
            'user-guide/secrets/index',
            'user-guide/secrets/bitwarden',
            'user-guide/secrets/onepassword',
          ],
        },
        {
          type: 'category',
          label: 'Egress proxy',
          collapsed: true,
          items: [
            'user-guide/egress/index',
            'user-guide/egress/iron-proxy',
            'user-guide/egress/network-isolation',
          ],
        },
        'user-guide/sessions',
        'user-guide/session-storage-recovery',
        'user-guide/profiles',
        'user-guide/profile-distributions',
        'user-guide/multi-profile-gateways',
        'user-guide/multi-connection-desktop',
        'user-guide/git-worktrees',
        'user-guide/docker',
        'user-guide/security',
        'user-guide/checkpoints-and-rollback',
      ],
    },
    {
      type: 'category',
      label: 'Features',
      collapsed: true,
      items: [
        'user-guide/features/overview',
        'user-guide/features/tool-gateway',
        {
          type: 'category',
          label: 'Core',
          items: [
            'user-guide/features/tools',
            'user-guide/features/document-extraction',
            'user-guide/features/tool-search',
            'user-guide/features/skills',
            'user-guide/features/lsp',
            'user-guide/features/curator',
            'user-guide/features/memory',
            'user-guide/features/memory-providers',
            'user-guide/features/honcho',
            'user-guide/features/context-files',
            'user-guide/features/context-references',
            'user-guide/features/mixture-of-agents',
            'user-guide/features/personality',
            'user-guide/features/skins',
            'user-guide/features/language-packs',
            'user-guide/features/plugins',
            'user-guide/features/built-in-plugins',
            'user-guide/features/plugin-catalog',
          ],
        },
        {
          type: 'category',
          label: 'Automation',
          items: [
            'user-guide/features/cron',
            'reference/automation-blueprints-catalog',
            'user-guide/features/delegation',
            'user-guide/features/kanban',
            'user-guide/features/codex-app-server-runtime',
            'user-guide/features/kanban-tutorial',
            'user-guide/features/kanban-worker-lanes',
            'user-guide/features/kanban-multi-gateway',
            'user-guide/features/goals',
            'user-guide/features/heartbeat',
            'user-guide/features/loops',
            'user-guide/features/code-execution',
            'user-guide/features/hooks',
            'user-guide/features/batch-processing',
          ],
        },
        {
          type: 'category',
          label: 'Media & Web',
          items: [
            'user-guide/features/voice-mode',
            'user-guide/features/wake-word',
            'user-guide/features/web-search',
            'user-guide/features/x-search',
            'user-guide/features/browser',
            'user-guide/features/credential-vault',
            'user-guide/features/computer-use',
            'user-guide/features/bot-screen',
            'user-guide/features/vision',
            'user-guide/features/image-generation',
            'user-guide/features/pets',
            'user-guide/features/tts',
            'user-guide/features/deliverable-mode',
          ],
        },
        {
          type: 'category',
          label: 'Management',
          items: [
            'user-guide/features/web-dashboard',
            'user-guide/features/extending-the-dashboard',
            'user-guide/features/api-server',
            'user-guide/features/subscription-proxy',
          ],
        },
        {
          type: 'category',
          label: 'Skills',
          collapsed: true,
          items: [
            'reference/skills-catalog',
            'reference/optional-skills-catalog',
            {
              type: 'category',
              label: 'Bundled',
              collapsed: true,
              items: [
                {
                  type: 'category',
                  label: 'autonomous-ai-agents',
                  key: 'skills-bundled-autonomous-ai-agents',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/autonomous-ai-agents/autonomous-ai-agents-computer-use',
                    'user-guide/skills/bundled/autonomous-ai-agents/autonomous-ai-agents-hermes-agent',
                  ],
                },
                {
                  type: 'category',
                  label: 'media',
                  key: 'skills-bundled-media',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/media/media-gif-search',
                    'user-guide/skills/bundled/media/media-youtube-content',
                  ],
                },
                {
                  type: 'category',
                  label: 'research',
                  key: 'skills-bundled-research',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/research/research-arxiv',
                    'user-guide/skills/bundled/research/research-grounded-citations',
                    'user-guide/skills/bundled/research/research-llm-wiki',
                  ],
                },
                {
                  type: 'category',
                  label: 'software-development',
                  key: 'skills-bundled-software-development',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/software-development/software-development-codebase-inspection',
                    'user-guide/skills/bundled/software-development/software-development-dogfood',
                    'user-guide/skills/bundled/software-development/software-development-github',
                    'user-guide/skills/bundled/software-development/software-development-hermes-agent-skill-authoring',
                    'user-guide/skills/bundled/software-development/software-development-inspecting-hermes-desktop-dom',
                    'user-guide/skills/bundled/software-development/software-development-node-inspect-debugger',
                    'user-guide/skills/bundled/software-development/software-development-python-debugpy',
                    'user-guide/skills/bundled/software-development/software-development-requesting-code-review',
                    'user-guide/skills/bundled/software-development/software-development-simplify-code',
                    'user-guide/skills/bundled/software-development/software-development-spike',
                    'user-guide/skills/bundled/software-development/software-development-systematic-debugging',
                    'user-guide/skills/bundled/software-development/software-development-test-driven-development',
                  ],
                },
                {
                  type: 'category',
                  label: 'web',
                  key: 'skills-bundled-web',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/web/web-blocked-page-recovery',
                  ],
                },
              ],
            },
            {
              type: 'category',
              label: 'Optional',
              collapsed: true,
              items: [
                {
                  type: 'category',
                  label: 'communication',
                  key: 'skills-optional-communication',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/communication/communication-one-three-one-rule',
                  ],
                },
                {
                  type: 'category',
                  label: 'creative',
                  key: 'skills-optional-creative',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/creative/creative-concept-diagrams',
                    'user-guide/skills/optional/creative/creative-creative-ideation',
                    'user-guide/skills/optional/creative/creative-sketch',
                  ],
                },
                {
                  type: 'category',
                  label: 'dogfood',
                  key: 'skills-optional-dogfood',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/dogfood/dogfood-adversarial-ux-test',
                  ],
                },
                {
                  type: 'category',
                  label: 'productivity',
                  key: 'skills-optional-productivity',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/productivity/productivity-memento-flashcards',
                  ],
                },
                {
                  type: 'category',
                  label: 'research',
                  key: 'skills-optional-research',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/research/research-duckduckgo-search',
                    'user-guide/skills/optional/research/research-rss-feeds',
                    'user-guide/skills/optional/research/research-searxng-search',
                  ],
                },
                {
                  type: 'category',
                  label: 'software-development',
                  key: 'skills-optional-software-development',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/software-development/software-development-grill-me',
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Messaging Platforms',
      collapsed: true,
      items: [
        'user-guide/messaging/index',
        {
          type: 'category',
          label: 'Popular',
          items: [
            'user-guide/messaging/telegram',
            'user-guide/messaging/discord',
            'user-guide/messaging/slack',
            'user-guide/messaging/whatsapp',
            'user-guide/messaging/whatsapp-cloud',
            'user-guide/messaging/signal',
            'user-guide/messaging/email',
            'user-guide/messaging/sms',
          ],
        },
        {
          type: 'category',
          label: 'Microsoft 365',
          items: [
            'user-guide/messaging/teams',
            'user-guide/messaging/msgraph-webhook',
          ],
        },
        {
          type: 'category',
          label: 'Chinese platforms',
          items: [
            'user-guide/messaging/dingtalk',
            'user-guide/messaging/feishu',
            'user-guide/messaging/wecom',
            'user-guide/messaging/wecom-callback',
            'user-guide/messaging/weixin',
            'user-guide/messaging/qqbot',
            'user-guide/messaging/yuanbao',
          ],
        },
        {
          type: 'category',
          label: 'Other',
          items: [
            'user-guide/messaging/a2a',
            'user-guide/messaging/homeassistant',
            'user-guide/messaging/mattermost',
            'user-guide/messaging/matrix',
            'user-guide/messaging/bluebubbles',
            'user-guide/messaging/buzz',
            'user-guide/messaging/photon',
            'user-guide/messaging/google_chat',
            'user-guide/messaging/line',
            'user-guide/messaging/simplex',
            'user-guide/messaging/ntfy',
            'user-guide/messaging/irc',
            'user-guide/messaging/open-webui',
            'user-guide/messaging/relay',
            'user-guide/messaging/webhooks',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      collapsed: true,
      items: [
        'integrations/index',
        'integrations/nous-portal',
        'integrations/providers',
        'integrations/buzz',
        'user-guide/features/mcp',
        'user-guide/features/acp',
        'user-guide/features/provider-routing',
        'user-guide/features/fallback-providers',
        'user-guide/features/credential-pools',
      ],
    },
    {
      type: 'category',
      label: 'Guides & Tutorials',
      collapsed: true,
      items: [
        'guides/run-nemotron-3-ultra-free',
        'guides/run-hermes-with-nous-portal',
        'guides/tips',
        'guides/local-llm-on-mac',
        'guides/daily-briefing-bot',
        'guides/team-telegram-assistant',
        'guides/python-library',
        'guides/use-mcp-with-hermes',
        'guides/manage-hermes-cloud-with-mcp',
        'guides/use-soul-with-hermes',
        'guides/use-voice-mode-with-hermes',
        'guides/automate-with-cron',
        'guides/cron-script-only',
        'guides/automation-blueprints',
        'guides/cron-troubleshooting',
        'guides/work-with-skills',
        'guides/delegation-patterns',
        'guides/agent-email-address',
        'guides/github-pr-review-agent',
        'guides/webhook-github-pr-review',
        'guides/migrate-from-openclaw',
        'guides/aws-bedrock',
        'guides/google-vertex',
        'guides/azure-foundry',
        'guides/xai-grok-oauth',
        'guides/oauth-over-ssh',
        'guides/microsoft-graph-app-registration',
      ],
    },
    {
      type: 'category',
      label: 'Developer Guide',
      collapsed: true,
      items: [
        'developer-guide/contributing',
        'developer-guide/worktree-ui-dev',
        {
          type: 'category',
          label: 'Architecture',
          items: [
            'developer-guide/architecture',
            'developer-guide/codebase-ownership',
            'developer-guide/agent-loop',
            'developer-guide/prompt-assembly',
            'developer-guide/context-compression-and-caching',
            'developer-guide/micro-compaction',
            'developer-guide/gateway-internals',
            'developer-guide/gateway-session-lifecycle',
            'developer-guide/multiplexing-gateway',
            'developer-guide/completion-backlog-delivery',
            'developer-guide/session-storage',
            'developer-guide/state-db-recovery',
            'developer-guide/provider-runtime',
            'developer-guide/programmatic-integration',
          ],
        },
        {
          type: 'category',
          label: 'Extending',
          items: [
            'developer-guide/adding-tools',
            'developer-guide/adding-providers',
            'developer-guide/adding-platform-adapters',
            {
              type: 'category',
              label: 'Plugins',
              link: {type: 'doc', id: 'developer-guide/plugins/index'},
              items: [
                'developer-guide/plugin-llm-access',
                'developer-guide/observer-hooks',
                'developer-guide/middleware',
                'developer-guide/subagent-lifecycle-api',
                'developer-guide/desktop-plugin-sdk',
                'developer-guide/memory-provider-plugin',
                'developer-guide/context-engine-plugin',
                'developer-guide/secret-source-plugin',
                'developer-guide/model-provider-plugin',
                'developer-guide/image-gen-provider-plugin',
                'developer-guide/video-gen-provider-plugin',
                'developer-guide/web-search-provider-plugin',
                'developer-guide/browser-provider-plugin',
                'developer-guide/terminal-environment-plugin',
                'developer-guide/plugins/application-declarations',
                'developer-guide/plugins/catalog-submission',
              ],
            },
            'developer-guide/creating-skills',
            'developer-guide/extending-the-cli',
          ],
        },
        {
          type: 'category',
          label: 'Internals',
          items: [
            'developer-guide/tools-runtime',
            'developer-guide/browser-supervisor',
            'developer-guide/acp-internals',
            'developer-guide/cron-internals',
            'developer-guide/chronos-managed-cron-contract',
            'developer-guide/egress-internals',
            'developer-guide/gateway-monitoring',
            'developer-guide/relay-connector-contract',
            'developer-guide/relay-shared-metrics',
            'developer-guide/streaming-tts',
            'developer-guide/billing-lifecycle',
            'developer-guide/trajectory-format',
          ],
        },
        {
          type: 'category',
          label: 'Packaging & Releases',
          items: [
            'developer-guide/source-update-completion',
            'developer-guide/shared-bundle-builds',
            'developer-guide/stable-releases',
            'developer-guide/macos-bundle-updates',
            'developer-guide/pm-audit-status',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        {
          type: 'category',
          label: 'Command Reference',
          items: [
            'reference/cli-commands',
            'reference/package-management',
            'reference/slash-commands',
            'reference/profile-commands',
          ],
        },
        {
          type: 'category',
          label: 'Configuration Reference',
          items: [
            'reference/environment-variables',
            'reference/mcp-config-reference',
            'reference/model-catalog',
          ],
        },
        {
          type: 'category',
          label: 'Tools & Skills Reference',
          items: [
            'reference/tools-reference',
            'reference/toolsets-reference',
            'reference/skills-catalog',
            'reference/optional-skills-catalog',
          ],
        },
        'reference/cli-symbols',
        'reference/faq',
      ],
    },
  ],
};

export default sidebars;
